import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const onest = localFont({
	src: "./fonts/Onest-VariableFont_wght.ttf",
	variable: "--font-onest",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="ru" className={onest.className}>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
